### ISSUE TITLE
Remove numeric url_path values in migrated content 

### ISSUE THREAD

**Issue by carakey** [osulp/ojs#16]
Remove the url_path values that are all numbers for all current migrated content in journals3 production. Leave non-numeric values in place. 

Part of resolving #15.  

_Should not affect currently public Journals3 content (OLAQ, which has non-numeric url_path values; and NWeLearn, which has NULL url_path values)._

Reference: Database table exported to CSV, with numeric values highlighted -
https://docs.google.com/spreadsheets/d/1WriGDiBm9nqsYM7JFrW8codGjLSR4B7neFr_EQeru2E/edit#gid=193614333&range=879:879

**Comment by wickr** [comment]
Replaced all numeric values in the prod database with NULL values, 500 rows affected.

Still looking at how best to map/redirect these OJS2 numeric values to the new ones, and if journal short ID needs to be included as well. I think that's more in the realm of #32 so will probably continue that there.

**Comment by carakey** [comment]
@wickr 

In the latest tracking spreadsheet (#31 ), I used the IDlookup sheet to construct the expected OJS3 URLs for the migrated content. I got 516 hits -- and 16 of them were on Issue items.

I've done some random spot checking and so far all the URLs for Articles are resolving as expected, so that's pretty decent as a quick QA method. 

It looks like Issue items don't appear in the IDlookup sheet -- which makes sense, given those are submission IDs. There are 16 that did match, though, and the constructed URLs are not valid. I think they're possibly dupes or otherwise bad data. I can look more into it, and into whether the numeric IDs also need to get swapped for Issues. 

FWIW this sheet could also be usable for redirects.

**Comment by carakey** [comment]
@wickr 

Answering some questions posed in the previous comment:

1. Migrated issue items with numeric IDs in OJS2 still have the same numeric IDs in OJS3.
1. Those 16 issue matches to the IDlookup sheet were false positives - my lookup formula was not quite smart enough. They've been fixed in the spreadsheet.
1. Yes, the numeric Issue IDs will also need to be swapped; issue items with numeric IDs can also not be edited and re-saved in 3.3.x (Error on save: "The URL path can not be a number.") If this is not as straightforward in the database as the submission IDs, could we use the volume and number to construct a string ID, somewhat like we did for OLAQ? A list of the existing numeric IDs for issues could be pulled from the spreadsheet if it's useful.

**Comment by wickr** [comment]
@carakey 
Ok thanks for the update, I looked and there's also a 'url_path' column in the issues table. There's 72 values that are numeric. I set all of those to NULL just like in the publications table.

**Comment by wickr** [comment]
Here's the prior listing that has the Issue ID mapping to url_path that I didn't see in your spreadsheet.
```
+----------+------------+----------+
| issue_id | journal_id | url_path |
+----------+------------+----------+
|      111 |         11 | 572      |
|      131 |         11 | 558      |
|      136 |         11 | 559      |
|      166 |         16 | 557      |
|      171 |         16 | 571      |
|      196 |         21 | 476      |
|      291 |         26 | 141      |
|      296 |         26 | 156      |
|      356 |         26 | 121      |
|      376 |         21 | 196      |
|      381 |         21 | 201      |
|      386 |         21 | 428      |
|      391 |         21 | 445      |
|      396 |         21 | 191      |
|      401 |         21 | 554      |
|      406 |         21 | 271      |
|      411 |         21 | 411      |
|      416 |         21 | 431      |
|      436 |         26 | 538      |
|      446 |         26 | 530      |
|      456 |         26 | 520      |
|      466 |         26 | 514      |
|      471 |         26 | 511      |
|      476 |         26 | 508      |
|      481 |         26 | 505      |
|      486 |         26 | 502      |
|      491 |         26 | 499      |
|      496 |         26 | 470      |
|      501 |         26 | 381      |
|      506 |         26 | 371      |
|      511 |         26 | 491      |
|      516 |         26 | 361      |
|      521 |         26 | 351      |
|      526 |         26 | 346      |
|      546 |         26 | 321      |
|      556 |         26 | 186      |
|      561 |         26 | 291      |
|      566 |         26 | 231      |
|      571 |         26 | 181      |
|      576 |         26 | 126      |
|      581 |         26 | 171      |
|      586 |         26 | 161      |
|      591 |         26 | 116      |
|      596 |         26 | 151      |
|      601 |         26 | 146      |
|      606 |         26 | 106      |
|      626 |          6 | 261      |
|      631 |          6 | 266      |
|      636 |          6 | 421      |
|      641 |          6 | 440      |
|      646 |          6 | 451      |
|      656 |          6 | 461      |
|      661 |          6 | 484      |
|      666 |          6 | 560      |
|      671 |         26 | 544      |
|      676 |         26 | 551      |
|      681 |         26 | 341      |
|      686 |         26 | 541      |
|      691 |         26 | 536      |
|      696 |         26 | 326      |
|      701 |         26 | 246      |
|      706 |         26 | 527      |
|      711 |         26 | 517      |
|      716 |         16 | 576      |
|      721 |         16 | 581      |
|      726 |         11 | 568      |
|      731 |         11 | 479      |
|      736 |         11 | 523      |
|      741 |         11 | 547      |
|      746 |         11 | 561      |
|      751 |         11 | 562      |
|      756 |         11 | 566      |
+----------+------------+----------+
72 rows in set (0.001 sec)
```

**Comment by carakey** [comment]
Great, thanks. I updated the spreadsheet and spot checked issue URLs. 72 issue rows matches up with expectations -- I got 71 hits in the spreadsheet, and looked into the missing one and it looks like we migrated pre-publication content that was subsequently removed from OJS2, or moved to a different issue, etc.

**Comment by carakey** [comment]
Last question: Content files - galleys and supplements. They also had url_paths specified in the import XML. 
If it's straightforward to do, I think we should swap them as well. That list isn't included in the spreadsheet, but I could pull it out of the METS data ([over here](https://github.com/osulp/ojs/tree/master/migration_sample_data/xsl)).

**Comment by carakey** [comment]
I added another sheet with the file IDs included, [here](https://docs.google.com/spreadsheets/d/1cV8taNhO5kgVeyJRV0GWeL-ta5khHgSIsg_0pLTG0oM/edit#gid=141946193).

**Comment by wickr** [comment]
@carakey Ok I changed numeric values to NULL in the `publication_galleys` table as well which looks to have supplements too. 1647 values were changed (out of 1725 total entries).

**Comment by carakey** [comment]
Thanks @wickr, spot checking looks good, but I can't verify the numbers. They don't match up with anything that's obvious to me in the spreadsheet.
