### ISSUE TITLE
Install paid theme

### ISSUE THREAD

**Issue by carakey** [osulp/ojs#18]
Franny emailed theme files to Ryan for current version.

**Comment by wickr** [comment]
`Theme #11` files installed and enabled on both staging and prod.

<img width="1415" alt="Screenshot 2023-04-12 at 11 08 31 PM" src="https://user-images.githubusercontent.com/2293544/231669103-91223cb6-efe3-43d0-a358-f3b5695ad87a.png">

I switched to it on ojs-test's Demo Journal for a bit and it at least loaded.

@carakey ready for more testing

**Comment by wickr** [comment]
Closing this since the install part is done, and further config or tweaks are part of #19.
