### ISSUE TITLE
Implement redirects for journal contents

### ISSUE THREAD

**Issue by carakey** [osulp/ojs#32]
Each journal article will need a permanent redirect to account for changed publication IDs. Issues and Journal IDs should be the same. 
Journals can migrate independently of one another, though if more system-level redirects are needed for page views or viewers this could complicate timings.

Once all content is migrated from OJSv2 we need to make `journals` be the primary domain again, though `journals3` needs to continue to resolve and redirect permanently.

OJS2 issue: http://journals.library.oregonstate.edu/index.php/CatalogOSAC/issue/view/547
OJS3 issue: https://journals3.library.oregonstate.edu/CatalogOSAC/issue/view/547

OJS2 article: http://journals.library.oregonstate.edu/index.php/CatalogOSAC/article/view/4480
OJS3 article: https://journals3.library.oregonstate.edu/CatalogOSAC/article/view/5511

### Configure
- [ ] Permanent redirect from `journals3` to `journals` domain
- [ ] Handle older http links
- [ ] remove index.php from any old links
- [ ] Permanent redirects for Journal short ID changes
- [ ] Article-level redirects with journal ID short IDs to handle publication ID changes
- [ ] Make sure any `url_path` values are not interfered with

**Comment by carakey** [comment]
I realize parts of this are covered above, but here is my list of the various complexities, as filtered through my rudimentary understanding of this stuff works.

- journals.library.oregonstate.edu = journals.oregondigital.org (with the latter being the preferred version). 

- All content currently on `journals3` redirects to the same location on `journals`
    - ((NWeLearn & OLAQ DOIs with `journals3` URLs will get updated as part of #35 )). 
    
- All the migrated content -- at issue, article, and file levels -- had to get new system generated IDs. I'm working on a CSV with a 1:1 replacement list for all issues, articles, and files. But first...
- __There were 58 instances where both pub ID + journal ID were reused by different objects in OJS 3, creating a redirect conflict. I'm working on deleting and replacing the objects with the reused IDs in OJS 3.__

    - EXCEPTIONS: 
        - A few supplementary files were not migrated for various reasons, and the redirect URLs provided in the CSV are to the parent object.
        
- Static pages for each site will be nearly the same, except: 
    - OJS 2 includes `index.php` in URLs
    - The `/about/*` page structure diverges between OJS 2 to 3. Do we need to specify redirects from OJS 2 `/about/*` subpages to the appropriate top-level OJS 3 `/about/` page?
    - CSV for static pages: [OJS Redirects - Static Sites.csv](https://github.com/osulp/ojs/files/11973019/OJS.Redirects.-.Static.Sites.csv)
- The UO journal "OURJ" has moved to a different system (UO's Scholars Bank). I have a redirect list using DOIs where available, and pointing to their issue archive otherwise: [OJS Redirects - OURJ.csv](https://github.com/osulp/ojs/files/11973032/OJS.Redirects.-.OURJ.csv)

**Comment by carakey** [comment]
@wickr The redirect list should be clean and tidy now. This has all issue, submission, and galley objects.

[OJS Redirects - Main.csv](https://github.com/osulp/ojs/files/11986735/OJS.Redirects.-.Main.csv)

**Comment by carakey** [comment]
@wickr Now the redirect list is ready. This CSV has the 1:1 replacement list for all content objects - issues, submissions, and galley files.
[OJS Redirects - Main.csv](https://github.com/osulp/ojs/files/11992374/OJS.Redirects.-.Main-2.csv)

**Comment by wickr** [comment]
Redirects combined together and added to the existing file: https://github.com/osulp/osulp-infra/blob/main/config/brpx-configs/ojs_rewrites.conf

**Comment by carakey** [comment]
The journal _Puncta_ (pjcp) is moving to another host institution. We changed the redirects for their site and content to point to their new homepage at https://puncta.journals.villanova.edu.
