### ISSUE TITLE
Unable to re-save imported Title & Abstract fields

### ISSUE THREAD

**Issue by carakey** [osulp/ojs#38]
The problem is, when I try to edit an imported submission's Title & Abstract fields, it fails to save. (Example: https://journals3.oregondigital.org/nat_history/article/view/5672; this one is missing some newlines in the abstract.) The error messages are not useful: 

- (Popup at top) "The form was not saved because 1 error(s) were encountered. Please correct these errors and try again.""
- (At bottom) "Please correct one error. Please enter the abstract of your article. Jump to next error" <-- Clicking doesn't point to anything obvious or bring up any new info boxes, etc. 

@wickr I think I've tracked down the bug, but need some back-end support to confirm/fix. 

I found this forum post - https://forum.pkp.sfu.ca/t/doesnt-save-changes-articles/70804 - pointing to NULL language code values in the locale attributes. Sure enough: in the OJS 3 Demo Journal I set up an issue with one affected submission, uploaded fresh and that doesn't allow re-saving, plus one unaffected older submission that I moved from a different issue that _does_ allow re-saving. Exporting this hybrid issue, I can see that a value is missing on `//publication/@locale` for the affected item but a value is present on the unaffected item. 

I confirmed this particular submission did have an "en_US" value on import, so OJS stripped it out. I don't think it's something I can fix either with a fresh import or in the UI.

**Comment by wickr** [comment]
Confirmed our database table matches the forum post, there's lots of NULL values in locale that match up with imports. So it should be a straightforward fix to set all values to 'en_US'

**Comment by wickr** [comment]
There were 294 entries in the submissions table with a locale value of NULL. I ran this to replace the values and confirmed all were updated. There are currently no rows with 'NULL' in the table.

`UPDATE submissions SET locale = 'en_US' WHERE locale IS NULL;`

**Comment by wickr** [comment]
Updated the database for the test instance as well.
