### ISSUE TITLE
"Distribution" settings page not loading in OJS-Test

### ISSUE THREAD

**Issue by carakey** [osulp/ojs#5]
In the ojs-test 3.3 system, in the admin dashboard, the Settings >> Distribution page fails to load and instead results in a blank white page. 

Tested in Safari and Firefox in multiple journals, with same result.

Tabs within the Distribution settings page in 3.1 include Indexing, Access, Payments, and Permissions.

**Comment by wickr** [comment]
The cause of this was our PHP image not having the `gettext` extension enabled. Now with that working, the full Distribution page displays as expected.

Distribution panel in 3.3 shows License, Search Indexing, Payments, Access, Archiving.
