### ISSUE TITLE
Unable to edit users in OJS-Test

### ISSUE THREAD

**Issue by carakey** [osulp/ojs#6]
Path: [journal] / Settings / Users & Roles / Users

Description: Under the user’s name in the list, click Edit User. Error reads “Failed Ajax request or invalid JSON returned.” Popup widget has “Edit User” header and X close button but is otherwise blank.

**Comment by wickr** [comment]
The cause of this was our PHP image not having the `gettext` extension enabled. Now with that working, the full Edit popup displays as expected.
