### ISSUE TITLE
Unable to edit contributors in OJS-Test

### ISSUE THREAD

**Issue by carakey** [osulp/ojs#7]
Path: [journal] / Submissions / [any submission] / Publication / Contributors 

Description: Unpublished the article in order to view/edit contributor information. Under the author's name in the list, clicked Edit. Error reads “Failed Ajax request or invalid JSON returned.” Popup widget has “Edit Contributor” header and X close button but is otherwise blank.  

similar to behavior in https://github.com/osulp/ojs/issues/6

**Comment by wickr** [comment]
The cause of this was our PHP image not having the `gettext` extension enabled. Now with that working, the full Edit popup displays as expected.

Tested a submitted but unassigned Submission and assigned 'admin' as a Contributor, then can see Edit link and popup works.
https://ojs-test.library.oregonstate.edu/ojs3_demo/workflow/index/5597/5
